/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DestinationId = IDL.Nat;
export const Destination = IDL.Record({
  'id' : DestinationId,
  'country' : IDL.Text,
  'name' : IDL.Text,
  'imageUrl' : IDL.Text,
});
export const TestimonialId = IDL.Nat;
export const Testimonial = IDL.Record({
  'id' : TestimonialId,
  'review' : IDL.Text,
  'name' : IDL.Text,
  'avatarUrl' : IDL.Text,
  'rating' : IDL.Float64,
});
export const PackageId = IDL.Nat;
export const TourPackage = IDL.Record({
  'id' : PackageId,
  'duration' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'destinations' : IDL.Vec(DestinationId),
  'rating' : IDL.Float64,
  'price' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addDestination' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [Destination],
      [],
    ),
  'addTestimonial' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
      [Testimonial],
      [],
    ),
  'addTourPackage' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
        IDL.Vec(DestinationId),
      ],
      [TourPackage],
      [],
    ),
  'deleteDestination' : IDL.Func([DestinationId], [], []),
  'deleteTestimonial' : IDL.Func([TestimonialId], [], []),
  'deleteTourPackage' : IDL.Func([PackageId], [], []),
  'getAllDestinations' : IDL.Func([], [IDL.Vec(Destination)], ['query']),
  'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getAllTourPackages' : IDL.Func([], [IDL.Vec(TourPackage)], ['query']),
  'getDestinationById' : IDL.Func([DestinationId], [Destination], ['query']),
  'getTestimonialById' : IDL.Func([TestimonialId], [Testimonial], ['query']),
  'getTourPackageById' : IDL.Func([PackageId], [TourPackage], ['query']),
  'updateDestination' : IDL.Func(
      [DestinationId, IDL.Text, IDL.Text, IDL.Text],
      [Destination],
      [],
    ),
  'updateTestimonial' : IDL.Func(
      [TestimonialId, IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
      [Testimonial],
      [],
    ),
  'updateTourPackage' : IDL.Func(
      [
        PackageId,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
        IDL.Vec(DestinationId),
      ],
      [TourPackage],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DestinationId = IDL.Nat;
  const Destination = IDL.Record({
    'id' : DestinationId,
    'country' : IDL.Text,
    'name' : IDL.Text,
    'imageUrl' : IDL.Text,
  });
  const TestimonialId = IDL.Nat;
  const Testimonial = IDL.Record({
    'id' : TestimonialId,
    'review' : IDL.Text,
    'name' : IDL.Text,
    'avatarUrl' : IDL.Text,
    'rating' : IDL.Float64,
  });
  const PackageId = IDL.Nat;
  const TourPackage = IDL.Record({
    'id' : PackageId,
    'duration' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'destinations' : IDL.Vec(DestinationId),
    'rating' : IDL.Float64,
    'price' : IDL.Float64,
  });
  
  return IDL.Service({
    'addDestination' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [Destination],
        [],
      ),
    'addTestimonial' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
        [Testimonial],
        [],
      ),
    'addTourPackage' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
          IDL.Vec(DestinationId),
        ],
        [TourPackage],
        [],
      ),
    'deleteDestination' : IDL.Func([DestinationId], [], []),
    'deleteTestimonial' : IDL.Func([TestimonialId], [], []),
    'deleteTourPackage' : IDL.Func([PackageId], [], []),
    'getAllDestinations' : IDL.Func([], [IDL.Vec(Destination)], ['query']),
    'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getAllTourPackages' : IDL.Func([], [IDL.Vec(TourPackage)], ['query']),
    'getDestinationById' : IDL.Func([DestinationId], [Destination], ['query']),
    'getTestimonialById' : IDL.Func([TestimonialId], [Testimonial], ['query']),
    'getTourPackageById' : IDL.Func([PackageId], [TourPackage], ['query']),
    'updateDestination' : IDL.Func(
        [DestinationId, IDL.Text, IDL.Text, IDL.Text],
        [Destination],
        [],
      ),
    'updateTestimonial' : IDL.Func(
        [TestimonialId, IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
        [Testimonial],
        [],
      ),
    'updateTourPackage' : IDL.Func(
        [
          PackageId,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
          IDL.Vec(DestinationId),
        ],
        [TourPackage],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };