/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Destination {
  'id' : DestinationId,
  'country' : string,
  'name' : string,
  'imageUrl' : string,
}
export type DestinationId = bigint;
export type PackageId = bigint;
export interface Testimonial {
  'id' : TestimonialId,
  'review' : string,
  'name' : string,
  'avatarUrl' : string,
  'rating' : number,
}
export type TestimonialId = bigint;
export interface TourPackage {
  'id' : PackageId,
  'duration' : bigint,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'destinations' : Array<DestinationId>,
  'rating' : number,
  'price' : number,
}
export interface _SERVICE {
  'addDestination' : ActorMethod<[string, string, string], Destination>,
  'addTestimonial' : ActorMethod<[string, string, number, string], Testimonial>,
  'addTourPackage' : ActorMethod<
    [string, string, bigint, number, number, string, Array<DestinationId>],
    TourPackage
  >,
  'deleteDestination' : ActorMethod<[DestinationId], undefined>,
  'deleteTestimonial' : ActorMethod<[TestimonialId], undefined>,
  'deleteTourPackage' : ActorMethod<[PackageId], undefined>,
  'getAllDestinations' : ActorMethod<[], Array<Destination>>,
  'getAllTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getAllTourPackages' : ActorMethod<[], Array<TourPackage>>,
  'getDestinationById' : ActorMethod<[DestinationId], Destination>,
  'getTestimonialById' : ActorMethod<[TestimonialId], Testimonial>,
  'getTourPackageById' : ActorMethod<[PackageId], TourPackage>,
  'updateDestination' : ActorMethod<
    [DestinationId, string, string, string],
    Destination
  >,
  'updateTestimonial' : ActorMethod<
    [TestimonialId, string, string, number, string],
    Testimonial
  >,
  'updateTourPackage' : ActorMethod<
    [
      PackageId,
      string,
      string,
      bigint,
      number,
      number,
      string,
      Array<DestinationId>,
    ],
    TourPackage
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];