/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type DestinationId = bigint;
export interface TourPackage {
    id: PackageId;
    duration: bigint;
    name: string;
    description: string;
    imageUrl: string;
    destinations: Array<DestinationId>;
    rating: number;
    price: number;
}
export interface Destination {
    id: DestinationId;
    country: string;
    name: string;
    imageUrl: string;
}
export type TestimonialId = bigint;
export type PackageId = bigint;
export interface Testimonial {
    id: TestimonialId;
    review: string;
    name: string;
    avatarUrl: string;
    rating: number;
}
export interface backendInterface {
    addDestination(name: string, imageUrl: string, country: string): Promise<Destination>;
    addTestimonial(name: string, avatarUrl: string, rating: number, review: string): Promise<Testimonial>;
    addTourPackage(name: string, description: string, duration: bigint, price: number, rating: number, imageUrl: string, destinationIds: Array<DestinationId>): Promise<TourPackage>;
    deleteDestination(id: DestinationId): Promise<void>;
    deleteTestimonial(id: TestimonialId): Promise<void>;
    deleteTourPackage(id: PackageId): Promise<void>;
    getAllDestinations(): Promise<Array<Destination>>;
    getAllTestimonials(): Promise<Array<Testimonial>>;
    getAllTourPackages(): Promise<Array<TourPackage>>;
    getDestinationById(id: DestinationId): Promise<Destination>;
    getTestimonialById(id: TestimonialId): Promise<Testimonial>;
    getTourPackageById(id: PackageId): Promise<TourPackage>;
    updateDestination(id: DestinationId, name: string, imageUrl: string, country: string): Promise<Destination>;
    updateTestimonial(id: TestimonialId, name: string, avatarUrl: string, rating: number, review: string): Promise<Testimonial>;
    updateTourPackage(id: PackageId, name: string, description: string, duration: bigint, price: number, rating: number, imageUrl: string, destinationIds: Array<DestinationId>): Promise<TourPackage>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addDestination(arg0: string, arg1: string, arg2: string): Promise<Destination> {
        if (this.processError) {
            try {
                const result = await this.actor.addDestination(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDestination(arg0, arg1, arg2);
            return result;
        }
    }
    async addTestimonial(arg0: string, arg1: string, arg2: number, arg3: string): Promise<Testimonial> {
        if (this.processError) {
            try {
                const result = await this.actor.addTestimonial(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTestimonial(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addTourPackage(arg0: string, arg1: string, arg2: bigint, arg3: number, arg4: number, arg5: string, arg6: Array<DestinationId>): Promise<TourPackage> {
        if (this.processError) {
            try {
                const result = await this.actor.addTourPackage(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTourPackage(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async deleteDestination(arg0: DestinationId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDestination(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDestination(arg0);
            return result;
        }
    }
    async deleteTestimonial(arg0: TestimonialId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTestimonial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTestimonial(arg0);
            return result;
        }
    }
    async deleteTourPackage(arg0: PackageId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTourPackage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTourPackage(arg0);
            return result;
        }
    }
    async getAllDestinations(): Promise<Array<Destination>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDestinations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDestinations();
            return result;
        }
    }
    async getAllTestimonials(): Promise<Array<Testimonial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTestimonials();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTestimonials();
            return result;
        }
    }
    async getAllTourPackages(): Promise<Array<TourPackage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTourPackages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTourPackages();
            return result;
        }
    }
    async getDestinationById(arg0: DestinationId): Promise<Destination> {
        if (this.processError) {
            try {
                const result = await this.actor.getDestinationById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDestinationById(arg0);
            return result;
        }
    }
    async getTestimonialById(arg0: TestimonialId): Promise<Testimonial> {
        if (this.processError) {
            try {
                const result = await this.actor.getTestimonialById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTestimonialById(arg0);
            return result;
        }
    }
    async getTourPackageById(arg0: PackageId): Promise<TourPackage> {
        if (this.processError) {
            try {
                const result = await this.actor.getTourPackageById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTourPackageById(arg0);
            return result;
        }
    }
    async updateDestination(arg0: DestinationId, arg1: string, arg2: string, arg3: string): Promise<Destination> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDestination(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDestination(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateTestimonial(arg0: TestimonialId, arg1: string, arg2: string, arg3: number, arg4: string): Promise<Testimonial> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTestimonial(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTestimonial(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateTourPackage(arg0: PackageId, arg1: string, arg2: string, arg3: bigint, arg4: number, arg5: number, arg6: string, arg7: Array<DestinationId>): Promise<TourPackage> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTourPackage(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTourPackage(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
